Repository GDG-on-Campus-KNU/4th-1st-Project-Inveed-FE, pull requests merged in 2025-05, with the labels that each got.

#24 issue #13: 버튼 컴포넌트 구현
  assets/images/google-logo.svg
  components/button/ColoredButton.tsx
  components/button/LoginButton.tsx
  components/button/OutlinedButton.tsx
  components/button/RoundButton.tsx
  package-lock.json
  package.json
  types/svg.d.ts
  utils/tw.js
Labels: 🎨스타일

#25 issue #14: 이달의 총지출 컴포넌트 구현
  assets/images/arrow.svg
  components/Home/TotalExpense.tsx
Labels: 🎨스타일

#27 issue #16: 수입지출내역 컴포넌트 구현
  components/budget/ExpenseItem.tsx
  components/budget/IncomeItem.tsx
  components/budget/iconMapper.ts
Labels: 🎨스타일

#28 issue #17: 거래내용 입력 컴포넌트 구현
  app/(tabs)/index.tsx
  components/budget/Input/TransactionInput.tsx
Labels: 🎨스타일

#29 issue #18: 카테고리 선택 컴포넌트 구현
  app/(tabs)/index.tsx
  components/budget/ExpenseItem.tsx
  components/budget/Input/SelectCategory.tsx
  components/budget/iconMapper.ts
Labels: 🎨스타일

#31 Feat-2
  app/(tabs)/index.tsx
  assets/plant.svg
  components/button/ColoredButton.tsx
  components/expense/ExpenseDetailItem.tsx
  components/search/SearchBar.tsx
  components/transfer/TransferNotification.tsx
  pages/expense/ExpenseDetailPage.tsx
  pages/transfer/TransferCheckPage.tsx
  pages/transfer/TransferNotificatonPage.tsx
  tailwind.config.js
Labels: ✨ 기능

#33 issue #32: 컴포넌트 색상 수
  app/(tabs)/index.tsx
  components/Home/TotalExpense.tsx
  components/budget/ExpenseItem.tsx
  components/budget/IncomeItem.tsx
  components/budget/Input/SelectCategory.tsx
  components/budget/Input/TransactionInput.tsx
  components/button/ColoredButton.tsx
  components/button/LoginButton.tsx
  components/button/OutlinedButton.tsx
  components/button/RoundButton.tsx
  components/expense/ExpenseDetailItem.tsx
  components/stock/InvestItem.tsx
Labels: 🎨스타일

#34 issue #19: 로그인 페이지 구현
  app/(tabs)/_layout.tsx
  app/(tabs)/budget.tsx
  app/(tabs)/explore.tsx
  app/(tabs)/stock.tsx
  app/(tabs)/transfer.tsx
  app/_layout.tsx
  app/login.tsx
  app/token.tsx
  assets/images/InveedLogo.svg
  assets/images/TextLogo.svg
  assets/images/hangukLogo.svg
  components/button/ColoredButton.tsx
  components/button/LoginButton.tsx
  components/input/Input.tsx
  constants/layout.ts
  package-lock.json
  package.json
  pages/auth/LoginPage.tsx
  pages/auth/TokenPage.tsx
  stores/useAuthStore.ts
Labels: ✨ 기능, 🎨스타일

#35 Feat-8: SearchPage, ExpensePatternAnalysisPage 구현
  components/search/RealTimeSearchKeyword.tsx
  components/search/SearchBadge.tsx
  components/search/SearchBar.tsx
  components/search/SearchKeyword.tsx
  pages/expense/ExpensePatternAnalysisPage.tsx
  pages/search/SearchPage.tsx
Labels: ✨ 기능
